services:
  delivery_db:
    image: bitnami/cassandra:latest
    container_name: delivery_db
    environment:
      - CASSANDRA_CLUSTER_NAME=delivery_db
      - CASSANDRA_CQL_PORT_NUMBER=5435
    ports:
      - "5435:5435"
    volumes:
      - ./db-init/delivery/init-delivery.cql:/docker-entrypoint-initdb.d/init-delivery.cql
  commerce_db:
    image: postgres:latest
    container_name: commerce_db
    environment:
      - POSTGRES_DB=commerce_db
      - POSTGRES_USER=commerce_db
      - POSTGRES_PASSWORD=commerce
      - POSTGRESQL_PORT_NUMBER: 5433
    ports:
      - "5433:5432"
    volumes:
      - ./db-init/commerce/init-commerce.sql:/docker-entrypoint-initdb.d/init-commerce.sql