apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack
    receivers:
      - uid: ce0eyk36u28zlb
        type: slack
        settings:
          url: https://hooks.slack.com/services/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
        disableResolveMessage: false
