apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack
    receivers:
      - uid: ce0eyk36u28zlb
        type: slack
        settings:
          url: ${GF_NOTIFIERS_CONTACTPOINT_URL}
        disableResolveMessage: false
