spring:
  application:
    name: delivery-service
  cassandra:
    port: 5435
    contact-points: localhost
    keyspace-name: delivery_keyspace
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 19096